export const NOTIFICATION_ADD = "NOTIFICATION_ADD"
export const NOTIFICATION_MARK_ALL = "NOTIFICATION_MARK_ALL"
export const NOTIFICATION_SET_IS_READ = "NOTIFICATION_SET_IS_READ"
export const NOTIFICATION_RESET = "NOTIFICATION_RESET"