export const SET_VIDEOS = "SET_VIDEOS"
export const ADD_VIDEO = "ADD_VIDEO"
export const DELETE_VIDEO = "DELETE_VIDEO"
export const GET_VIDEOS = "GET_VIDEOS"
export const RESET_VIDEOS = "RESET_VIDEOS"