// Action types
export const SET_PROFILE_PERSONAL = "SET_PROFILE_PERSONAL"
export const SET_PROFILE_LOCATION = "SET_PROFILE_LOCATION"
export const SET_PROFILE_EDUCATION = "SET_PROFILE_EDUCATION"
export const SET_PROFILE_SUBSCRIPTION = "SET_PROFILE_SUBSCRIPTION"
export const SET_PROFILE_META = "SET_PROFILE_META"

// Request types
export const SET_PROFILE_REQUEST = "SET_PROFILE_REQUEST"
export const SET_PROFILE_SUBSCRIPTION_REQUEST = "SET_PROFIE_SUBSCRIPTION_REQUEST"
