// Action types
export const SET_PROFILE_PERSONAL = "SET_PROFILE_PERSONAL"
export const SET_PROFILE_UNSUBSCRIBE_REQUEST = "SET_PROFILE_UNSUBSCRIBE_REQUEST"

// Request types
export const SET_PROFILE_REQUEST = "SET_PROFILE_REQUEST"
export const SET_PROFILE_SUBSCRIPTION_REQUEST = "SET_PROFIE_SUBSCRIPTION_REQUEST"
