// Action types
export const SET_PROFILE_PERSONAL = "SET_PROFILE_PERSONAL"
export const SET_PROFILE_UNSUBSCRIBE_REQUEST = "SET_PROFILE_UNSUBSCRIBE_REQUEST"
export const RESET_PROFILE = "RESET_PROFILE"
export const SET_PROFILE_VIDEOS = "SET_PROFILE_VIDEOS"
export const REMOVE_PROFILE_VIDEOS = "REMOVE_PROFILE_VIDEOS"

// Request types
export const SET_PROFILE_REQUEST = "SET_PROFILE_REQUEST"
export const SET_PROFILE_IMAGES_REQUEST = "SET_PROFILE_IMAGES_REQUEST"
export const SET_PROFILE_SUBSCRIPTION_REQUEST = "SET_PROFIE_SUBSCRIPTION_REQUEST"
