export const SET_CREATE_PROFILE_PERSONAL = "SET_CREATE_PROFILE_PERSONAL"
export const SET_CREATE_PROFILE_LOCATION = "SET_CREATE_PROFILE_LOCATION"
export const SET_CREATE_PROFILE_EDUCATION = "SET_CREATE_PROFILE_EDUCATION"